function getConfiguration(config) {
    // Esta función permite indicar valores de configuración generales para 
    // todos los dispositivos de este modelo.

    config.addressLabel = { en: "MAC address", es: "Dirección MAC" };
}

function getEndpoints(deviceAddress, endpoints) {
    // Esta función permite indicar la configuración inicial de los endpoints
    // cuando se crea un dispositivo de este modelo.

    var e = endpoints.addEndpoint("1", "1 Terra 31-1#17 - Humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("2", "2 Terra 31-2#17 - Humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("3", "3 Terra 31-3#17 - Humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("4", "4 Terra 34-1#17 - Humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("5", "5 Terra 34-1#6 - Salinidad Bulk de suelo", endpointType.genericSensor);
    e.variableTypeId = 1373;
    endpoints.addEndpoint("6", "6 Terra 34-1#31 - Temperatura de suelo", endpointType.temperatureSensor);
    var e = endpoints.addEndpoint("7", "7 Terra 34-2#17 - Humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("8", "8 Terra 34-2#6 - Salinidad Bulk de suelo", endpointType.genericSensor);
    e.variableTypeId = 1373;
    endpoints.addEndpoint("9", "9 Terra 34-2#31 - Temperatura de suelo", endpointType.temperatureSensor);
    var e = endpoints.addEndpoint("10", "10 Terra 34-3#17 - Humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("11", "11 Terra 34-3#6 - Salinidad Bulk de suelo", endpointType.genericSensor);
    e.variableTypeId = 1373;
    endpoints.addEndpoint("12", "12 Terra 34-3#31 - Temperatura de suelo", endpointType.temperatureSensor);
    endpoints.addEndpoint("13", "13 Compteur#37 Contador de riego", endpointType.volumeSensor);
    endpoints.addEndpoint("14", "14 Drenaje#37 - Drenaje de riego", endpointType.volumeSensor);
    endpoints.addEndpoint("15", "15 SHT#31 - Temperatura ambiente", endpointType.temperatureSensor);
    endpoints.addEndpoint("16", "16 SHT#35 - Humedad relativa", endpointType.humiditySensor);
    var e = endpoints.addEndpoint("17", "17 Dendro tronco#89 - Dendrómetro de tronco", endpointType.genericSensor);
    e.variableTypeId = 1374;
    var e = endpoints.addEndpoint("18", "18 Envirop8#17 - Humedad de suelo (1)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("19", "19 Envirop8#17 - Humedad de suelo (2)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("20", "20 Envirop8#17 - Humedad de suelo (3)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("21", "21 Envirop8#17 - Humedad de suelo (4)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("22", "22 Envirop8#17 - Humedad de suelo (5)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("23", "23 Envirop8#17 - Humedad de suelo (6)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("24", "24 Envirop8#17 - Humedad de suelo (7)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("25", "25 Envirop8#17 - Humedad de suelo (8)", endpointType.genericSensor);
    e.variableTypeId = 1372;
    endpoints.addEndpoint("26", "26 Envirop8#31 - Temperatura de suelo (1)", endpointType.temperatureSensor);
    endpoints.addEndpoint("27", "27 Envirop8#31 - Temperatura de suelo (2)", endpointType.temperatureSensor);
    endpoints.addEndpoint("28", "28 Envirop8#31 - Temperatura de suelo (3)", endpointType.temperatureSensor);
    endpoints.addEndpoint("29", "29 Envirop8#31 - Temperatura de suelo (4)", endpointType.temperatureSensor);
    endpoints.addEndpoint("30", "30 Envirop8#31 - Temperatura de suelo (5)", endpointType.temperatureSensor);
    endpoints.addEndpoint("31", "31 Envirop8#31 - Temperatura de suelo (6)", endpointType.temperatureSensor);
    endpoints.addEndpoint("32", "32 Envirop8#31 - Temperatura de suelo (7)", endpointType.temperatureSensor);
    endpoints.addEndpoint("33", "33 Envirop8#31 - Temperatura de suelo (8)", endpointType.temperatureSensor);
    var e = endpoints.addEndpoint("34", "34 Envirop8#4 - Salinidad Bulk de suelo (1)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("35", "35 Envirop8#4 - Salinidad Bulk de suelo (2)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("36", "36 Envirop8#4 - Salinidad Bulk de suelo (3)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("37", "37 Envirop8#4 - Salinidad Bulk de suelo (4)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("38", "38 Envirop8#4 - Salinidad Bulk de suelo (5)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("39", "39 Envirop8#4 - Salinidad Bulk de suelo (6)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("40", "40 Envirop8#4 - Salinidad Bulk de suelo (7)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("41", "41 Envirop8#4 - Salinidad Bulk de suelo (8)", endpointType.genericSensor);
    e.variableTypeId = 1373;
    var e = endpoints.addEndpoint("42", "42 Solar#12 - Radiación solar", endpointType.genericSensor);
    e.variableTypeId = 1382;
    var e = endpoints.addEndpoint("43", "43 ECRN-100#43 - Pluviometro", endpointType.genericSensor);
    e.variableTypeId = 1383;
    var e = endpoints.addEndpoint("44", "44 WindDirection#38 - Dirección del viento", endpointType.genericSensor);
    e.variableTypeId = 1384;
    var e = endpoints.addEndpoint("45", "45 WindSpeed#26 - Velocidad de viento", endpointType.genericSensor);
    e.variableTypeId = 1385;
    var e = endpoints.addEndpoint("46", "46 GustWindSpeed#26 - Ráfagas de viento", endpointType.genericSensor);
    e.variableTypeId = 1385;
    var e = endpoints.addEndpoint("47", "47 PAR#44 - Radiación fotosinteticamente activa", endpointType.genericSensor);
    e.variableTypeId = 1386;
    endpoints.addEndpoint("48", "48 AtPressure#39 - Presión atmosférica", endpointType.pressureSensor);
    endpoints.addEndpoint("49", "49 VSOLAR - Voltaje de placa solar", endpointType.voltageSensor);
    endpoints.addEndpoint("50", "50 BATT - Batería", endpointType.voltageSensor);
    endpoints.addEndpoint("51", "51 Batt Ch Current - Corriente de carga de batería", endpointType.currentSensor);
    var e = endpoints.addEndpoint("52", "52 Pulse", endpointType.genericSensor);
    e.variableTypeId = 1376;
    var e = endpoints.addEndpoint("53", "53 Pulse acumulado", endpointType.genericSensor);
    e.variableTypeId = 1376;
    var e = endpoints.addEndpoint("54", "54 Pulse diario", endpointType.genericSensor);
    e.variableTypeId = 1376;
    var e = endpoints.addEndpoint("55", "55 Tiempo entre muestra en horas", endpointType.genericSensor);
    e.variableTypeId = 1387;
    var e = endpoints.addEndpoint("56", "56 Tiempo entre muestra en minutos", endpointType.genericSensor);
    e.variableTypeId = 1388;
    var e = endpoints.addEndpoint("57", "57 Tiempo de riego diario", endpointType.genericSensor);
    e.variableTypeId = 1389;
    var e = endpoints.addEndpoint("58", "58 Pulse caudal diario", endpointType.genericSensor);
    e.variableTypeId = 1390;
    var e = endpoints.addEndpoint("59", "59 Pulse drenaje", endpointType.genericSensor);
    e.variableTypeId = 1376;
    var e = endpoints.addEndpoint("60", "60 Pulse drenaje acumulado", endpointType.genericSensor);
    e.variableTypeId = 1376;
    var e = endpoints.addEndpoint("61", "61 Pulse drenaje diario", endpointType.genericSensor);
    e.variableTypeId = 1391;
    var e = endpoints.addEndpoint("62", "62 Pulse drenaje diario - Porcentaje", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("63", "63 Nº de riegos diarios", endpointType.genericSensor);
    e.variableTypeId = 1379;
    var e = endpoints.addEndpoint("64", "64 Pulse acumulado max", endpointType.genericSensor);
    e.variableTypeId = 1376;
    var e = endpoints.addEndpoint("65", "65 Porcentaje de drenaje por riego", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("66", "66 Valor máximo dendrómetro día", endpointType.genericSensor);
    e.variableTypeId = 1374;
    var e = endpoints.addEndpoint("67", "67 Valor mínimo dendrómetro día", endpointType.genericSensor);
    e.variableTypeId = 1374;
    var e = endpoints.addEndpoint("68", "68 Máxima contracción diaria - MDS", endpointType.genericSensor);
    e.variableTypeId = 1374;
    var e = endpoints.addEndpoint("69", "69 Tasa de crecimiento del tronco - TGR", endpointType.genericSensor);
    e.variableTypeId = 1374;
    var e = endpoints.addEndpoint("70", "70 Humedad calibrada de suelo Terra 31-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("71", "71 Humedad calibrada de suelo Terra 31-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("72", "72 Humedad calibrada de suelo Terra 31-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("73", "73 Humedad calibrada de suelo Terra 34-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("74", "74 Humedad calibrada de suelo Terra 34-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("75", "75 Humedad calibrada de suelo Terra 34-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("76", "76 Humedad calibrada de suelo Envirop8#17 1", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("77", "77 Humedad calibrada de suelo Envirop8#17 2", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("78", "78 Humedad calibrada de suelo Envirop8#17 3", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("79", "79 Humedad calibrada de suelo Envirop8#17 4", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("80", "80 Humedad calibrada de suelo Envirop8#17 5", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("81", "81 Humedad calibrada de suelo Envirop8#17 6", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("82", "82 Humedad calibrada de suelo Envirop8#17 7", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("83", "83 Humedad calibrada de suelo Envirop8#17 8", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("84", "84 Capacidad de campo Terra 31-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("85", "85 Capacidad de campo Terra 31-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("86", "86 Capacidad de campo Terra 31-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("87", "87 Capacidad de campo Terra 34-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("88", "88 Capacidad de campo Terra 34-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("89", "89 Capacidad de campo Terra 34-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("90", "90 Capacidad de campo Envirop8#17 1", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("91", "91 Capacidad de campo Envirop8#17 2", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("92", "92 Capacidad de campo Envirop8#17 3", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("93", "93 Capacidad de campo Envirop8#17 4", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("94", "94 Capacidad de campo Envirop8#17 5", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("95", "95 Capacidad de campo Envirop8#17 6", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("96", "96 Capacidad de campo Envirop8#17 7", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("97", "97 Capacidad de campo Envirop8#17 8", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("98", "98 Punto de marchitez permanente Terra 31-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("99", "99 Punto de marchitez permanente Terra 31-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("100", "100 Punto de marchitez permanente Terra 31-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("101", "101 Punto de marchitez permanente Terra 34-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("102", "102 Punto de marchitez permanente Terra 34-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("103", "103 Punto de marchitez permanente Terra 34-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("104", "104 Punto de marchitez permanente Envirop8#17 1", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("105", "105 Punto de marchitez permanente Envirop8#17 2", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("106", "106 Punto de marchitez permanente Envirop8#17 3", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("107", "107 Punto de marchitez permanente Envirop8#17 4", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("108", "108 Punto de marchitez permanente Envirop8#17 5", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("109", "109 Punto de marchitez permanente Envirop8#17 6", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("110", "110 Punto de marchitez permanente Envirop8#17 7", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("111", "111 Punto de marchitez permanente Envirop8#17 8", endpointType.genericSensor);
    e.variableTypeId = 1378;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("112", "112 Media humedad de suelo", endpointType.genericSensor);
    e.variableTypeId = 1372;
  /*  var e = endpoints.addEndpoint("113", "113 Media humedad de suelo Terra 31-2#17", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("114", "114 Media humedad de suelo Terra 31-3#17", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("115", "115 Media humedad de suelo Terra 34-1#17", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("116", "116 Media humedad de suelo Terra 34-2#17", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("117", "117 Media humedad de suelo Terra 34-3#17", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("118", "118 Media humedad de suelo Envirop8#17 1", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("119", "119 Media humedad de suelo Envirop8#17 2", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("120", "120 Media humedad de suelo Envirop8#17 3", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("121", "121 Media humedad de suelo Envirop8#17 4", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("122", "122 Media humedad de suelo Envirop8#17 5", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("123", "123 Media humedad de suelo Envirop8#17 6", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("124", "124 Media humedad de suelo Envirop8#17 7", endpointType.genericSensor);
    e.variableTypeId = 1372;
    var e = endpoints.addEndpoint("125", "125 Media humedad de suelo Envirop8#17 8", endpointType.genericSensor);
    e.variableTypeId = 1372;
   */
    var e = endpoints.addEndpoint("126", "126 Media humedad calibrada de suelo", endpointType.genericSensor);
    e.variableTypeId = 1378;
  /*  var e = endpoints.addEndpoint("127", "127 Media humedad calibrada de suelo Terra 31-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("128", "128 Media humedad calibrada de suelo Terra 31-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("129", "129 Media humedad calibrada de suelo Terra 34-1#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("130", "130 Media humedad calibrada de suelo Terra 34-2#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("131", "131 Media humedad calibrada de suelo Terra 34-3#17", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("132", "132 Media humedad calibrada de suelo Envirop8#17 1", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("133", "133 Media humedad calibrada de suelo Envirop8#17 2", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("134", "134 Media humedad calibrada de suelo Envirop8#17 3", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("135", "135 Media humedad calibrada de suelo Envirop8#17 4", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("136", "136 Media humedad calibrada de suelo Envirop8#17 5", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("137", "137 Media humedad calibrada de suelo Envirop8#17 6", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("138", "138 Media humedad calibrada de suelo Envirop8#17 7", endpointType.genericSensor);
    e.variableTypeId = 1378;
    var e = endpoints.addEndpoint("139", "139 Media humedad calibrada de suelo Envirop8#17 8", endpointType.genericSensor);
    e.variableTypeId = 1378;
 
 */ var e = endpoints.addEndpoint("140", "140 Salinidad Pore EC de suelo", endpointType.genericSensor);
    e.variableTypeId = 1373;
    endpoints.addEndpoint("141", "141 Temperatura máxima", endpointType.temperatureSensor);
    endpoints.addEndpoint("142", "142 Temperatura mínima", endpointType.temperatureSensor);
    endpoints.addEndpoint("143", "143 Temperatura media", endpointType.temperatureSensor);
    endpoints.addEndpoint("144", "144 SVP Presión de vapor saturado", endpointType.pressureSensor);
    endpoints.addEndpoint("145", "145 DVP Déficit de presión de vapor", endpointType.pressureSensor);
    var e = endpoints.addEndpoint("146", "146 Radiación solar acumulada", endpointType.genericSensor);
    e.variableTypeId = 1392;
    var e = endpoints.addEndpoint("147", "147 Horas frío día", endpointType.genericSensor);
    e.variableTypeId = 1387;
    var e = endpoints.addEndpoint("148", "148 Horas frío campaña", endpointType.genericSensor);
    e.variableTypeId = 1387;
    var e = endpoints.addEndpoint("149", "149 Z", endpointType.genericSensor);
    e.variableTypeId = 1379;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("150", "150 X", endpointType.genericSensor);
    e.variableTypeId = 1380;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("151", "151 Y", endpointType.genericSensor);
    e.variableTypeId = 1381;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("152", "152 Fecha y hora de muestreo anterior", endpointType.genericSensor);
    e.variableTypeId = 1395;
    var e = endpoints.addEndpoint("153", "153 Acumulador hora tiempo de riego", endpointType.genericSensor);
    e.variableTypeId = 1396;
    var e = endpoints.addEndpoint("154", "154 Z Drenaje", endpointType.genericSensor);
    e.variableTypeId = 1379;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("155", "155 X Drenaje", endpointType.genericSensor);
    e.variableTypeId = 1380;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("156", "156 Y Drenaje", endpointType.genericSensor);
    e.variableTypeId = 1381;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("157", "157 Acumulador número de eventos", endpointType.genericSensor);
    e.variableTypeId = 1379;
    var e = endpoints.addEndpoint("158", "158 Fecha inicio de campaña", endpointType.genericSensor);
    e.variableTypeId = 1397;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("159", "159 Fecha final de campaña", endpointType.genericSensor);
    e.variableTypeId = 1398;
    e.accessType = endpointAccessType.readWrite;
    endpoints.addEndpoint("160", "160 Humedad relativa media diaria", endpointType.humiditySensor);
    var e = endpoints.addEndpoint("161", "161 Velocidad del viento media diaria", endpointType.genericSensor);
    e.variableTypeId = 1385;
    endpoints.addEndpoint("162", "162 DSVP Presión de vapor saturado Diario", endpointType.pressureSensor);
    endpoints.addEndpoint("163", "163 ADVP Presión de vapor Actual Diario", endpointType.pressureSensor);
    var e = endpoints.addEndpoint("164", "164 Pendiente de la curva de presión de vapor", endpointType.genericSensor);
    e.variableTypeId = 1399;
    endpoints.addEndpoint("165", "165 Presion atmosferica calculada diaria", endpointType.pressureSensor);
    var e = endpoints.addEndpoint("166", "166 Constante psicrométrica (γ)", endpointType.genericSensor);
    e.variableTypeId = 1399;
    var e = endpoints.addEndpoint("167", "167 Evapotranspiración de referencia (ET₀)", endpointType.genericSensor);
    e.variableTypeId = 1400;
    var e = endpoints.addEndpoint("168", "168 Latitud", endpointType.genericSensor);
    e.variableTypeId = 1401;
    e.accessType = endpointAccessType.readWrite;
    var e = endpoints.addEndpoint("169", "169 Altitud", endpointType.genericSensor);
    e.variableTypeId = 1402;
    e.accessType = endpointAccessType.readWrite;
}

function validateDeviceAddress(address, result) {
    // Esta función permite validar la dirección de un dispositivo, cuando el usuario 
    // lo está creando. Si el dispositivo tiene reglas de validación especiales para 
    // la dirección, pueden verificarse aquí y devolver un mensaje de error en 
    // caso de que el formato de la dirección sea incorrecto.
}

function updateDeviceUIRules(device, rules) {
    // Esta función permite especificar reglas de interfaz de usuario en el nivel de 
    // dispositivo. Por ejemplo, es posible habilitar o deshabilitar la creación 
    // de endpoints manualmente al dispositivo después de que se creó.
}

function updateEndpointUIRules(endpoint, rules) {
    // Esta función permite especificar reglas de interfaz de usuario para cada
    // endpoint del dispositivo. Por ejemplo, es posible habilitar o inhabilitar la
    // eliminación de endpoints, o la edición de subtipo de endpoint.
    rules.canDelete = true;
    rules.canCreate = true;
    rules.canEditSubtype = true;
}